baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
width = '1920'
height = '1080'

